version: '3'

services:
  web:
    build: .
    container_name: web
    entrypoint: /entrypoint.sh
    depends_on:
      - db
    ports:
    - '80:80'

#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:80
#    volumes:
#      - .:/code
#    ports:
#      - '80:80'
#    entrypoint: /entrypoint.sh
#    depends_on:
#      - db

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: